# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{loose_tight_dictionary}
  s.version = "0.0.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Seamus Abshere"]
  s.date = %q{2011-03-02}
  s.description = %q{Create dictionaries that link rows between two tables (left and right) using loose matching (string similarity) by default and tight matching (regexp) by request.}
  s.email = %q{seamus@abshere.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "examples/first_name_matching.rb",
     "examples/icao-bts.rb",
     "examples/icao-bts.xls",
     "lib/loose_tight_dictionary.rb",
     "loose_tight_dictionary.gemspec",
     "test/helper.rb",
     "test/test_loose_tight_dictionary.rb"
  ]
  s.homepage = %q{http://github.com/seamusabshere/loose_tight_dictionary}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Allows iterative development of dictionaries for big data sets.}
  s.test_files = [
    "test/helper.rb",
     "test/test_loose_tight_dictionary.rb",
     "examples/first_name_matching.rb",
     "examples/icao-bts.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<remote_table>, [">= 0.2.19"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.4"])
      s.add_runtime_dependency(%q<andand>, [">= 1.3.1"])
      s.add_runtime_dependency(%q<amatch>, [">= 0.2.5"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<remote_table>, [">= 0.2.19"])
      s.add_dependency(%q<activesupport>, [">= 2.3.4"])
      s.add_dependency(%q<andand>, [">= 1.3.1"])
      s.add_dependency(%q<amatch>, [">= 0.2.5"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<remote_table>, [">= 0.2.19"])
    s.add_dependency(%q<activesupport>, [">= 2.3.4"])
    s.add_dependency(%q<andand>, [">= 1.3.1"])
    s.add_dependency(%q<amatch>, [">= 0.2.5"])
  end
end

